name: FancyMenu-Plugin
version: '1.5'
main: de.keksuccino.fancymenu.FancyMenu
api-version: '1.20'
authors: [ Happy_FZM , Keksuccino ]
description: FancyMenu Mod for Bukkit
permissions:
  minecraft.command.closeguiscreen:
    default: true
  minecraft.command.openguiscreen:
    default: true
  minecraft.command.fmvariable:
    default: true
  minecraft.command.fmlayout:
    default: true